baseURL: https://mohkale.gitlab.io
languageCode: en-us
# theme: default

title: Mohsin Kaleem
params:
  name: Mohsin Kaleem
  subtitle: I'm a developer
  subtitles:
    - A habitual hacker (⌐■_■)
    - A lifelong weeb (ﾉ◕ヮ◕)ﾉ*:･ﾟ✧
    - (lost (in (lisp (parens))))
    # - a frequent gamer
  address:
    name: 9 Birchlands Drive
    postcode: S4 8BX
    town: Sheffield
    county: South Yorkshire
    country: United Kingdom
  contact:
    # TODO test
    phone: "tel:+07743287831"
    mail: mailto:mohkalex@gmail.com
    github: https://github.com/mohkale
    gitlab: https://gitlab.com/mohkale
    myanimelist: https://myanimelist.net/profile/mohkalex
    linkedin: https://www.linkedin.com/in/mohkale
    # upwork: https://www.upwork.com/o/profiles/users/~01b9386b9361c6cba7/
    upwork: http://kisara.moe/r/upwork

themes: []
  # - name: default
  #   repo: https://github.com/budparr/gohugo-theme-ananke.git
  #   branch: master
  # - name: terminal
  #   repo: https://github.com/panr/hugo-theme-terminal

taxonomies:
  category: categories
  tag: tags

permalinks:
  posts: /posts/:year/:month/:day/:title/

ignoreFiles:
  - '^\\.#'
  - 'resume/ACV/.*'

frontmatter:
  date:
    - :filename
    - :default

Paginate: 1000000 # WE DON'T NEED PAGINATION MWAHAHAHAAHAHAH

# make relative URLs stay relative.
canonifyURLs: false
enableEmoji: true
enableRobotsTXT: true

refLinksErrorLevel: WARNING

# configure paths
archetypeDir: arch/
assetDir: src/assets/
contentDir: src/content/
dataDir: src/data/
layoutDir: src/layouts
staticDir: src/static
configDir: etc/config
publishDir: var/public/
themesDir: vendor/
resourceDir: var/resources/

logFile: var/hugo.log

markup:
  # literally the only available engine that
  # let's you configure block-attributes :angry:.
  defaultMarkdownHandler: mmark
  highlight:
    noClasses: false
  goldmark:
    parser:
      # attribute:
      #   block: true
      #   title: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      unsafe: true

# add non-content entries to [[https://gohugo.io/content-management/menus/#add-non-content-entries-to-a-menu][menus]].
menu:
  nav:
    - identifier: tags
      url: /tags/
      weight: 30
    - identifier: resume
      url: /resume/index.pdf
      weight: 25

# Extra output formats, including a search index.
outputFormats:
  SearchIndex:
    mediaType: application/json
    baseName: searchindex
    isPlainText: true
    notAlternative: true

outputs:
  home: [HTML, RSS, JSON, SearchIndex]
  section: [HTML, RSS, JSON]

module:
  imports:
    - path: org/brain-hugo
