--- # gitlab CI/CD configuration file for mohkale.io
image: registry.gitlab.com/mohkale/mohkale.gitlab.io

stages:
  - setup
  - build
  - test
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: none

install:
  stage: setup
  script:
    # Fix access rights on private modules then fetch them. See [[https://stackoverflow.com/a/53758544/6247387][here]].
    - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/".insteadOf "git@gitlab.com:"
    - git submodule sync --recursive && git submodule update --init --recursive
    - bundle exec thor install:all
  artifacts:
    paths:
      - vendor/
      - .bundle/
      - node_modules/
      - Gemfile.lock
      - package-lock.json
      - yarn.lock
      - src/
      - var/themes

install-brain:
  stage: setup
  script:
    - bundle exec thor install:org
    - mkdir -p ~/.emacs.d/ && touch ~/.emacs.d/early-init.el
    # For some reason straight crashes the bootstrapper the first time?
    - bundle exec thor site:brain
  artifacts:
    paths:
      - vendor/org

build:
  stage: build
  script:
    - bundle exec thor site:build --output var/public/ --no-drafts --env production
    - ./bin/compress-assets -v var/public
  artifacts:
    paths:
      - var/public

test:
  stage: test
  script:
    - bundle exec thor test:site --output var/public/

pages:
  stage: deploy
  script:
    - mv var/public public
  artifacts:
    paths:
      - public
  only:
    # This job will only run on the 'master' branch.
    - master
